package pe.edu.unu.evaluacion.pojo;
// Generated 08/02/2016 11:38:29 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Curso generated by hbm2java
 */
public class Curso  implements java.io.Serializable {


     private Integer idCurso;
     private String idCurso2;
     private String codigoCurso;
     private String nombreCurso;
     private String nombreCursoAbreviado;
     private String registro;
     private Set semestreCursos = new HashSet(0);
     private Set encuestaDetalles = new HashSet(0);

    public Curso() {
    }

	
    public Curso(String codigoCurso, String nombreCurso, String registro) {
        this.codigoCurso = codigoCurso;
        this.nombreCurso = nombreCurso;
        this.registro = registro;
    }
    public Curso(String idCurso2, String codigoCurso, String nombreCurso, String nombreCursoAbreviado, String registro, Set semestreCursos, Set encuestaDetalles) {
       this.idCurso2 = idCurso2;
       this.codigoCurso = codigoCurso;
       this.nombreCurso = nombreCurso;
       this.nombreCursoAbreviado = nombreCursoAbreviado;
       this.registro = registro;
       this.semestreCursos = semestreCursos;
       this.encuestaDetalles = encuestaDetalles;
    }
   
    public Integer getIdCurso() {
        return this.idCurso;
    }
    
    public void setIdCurso(Integer idCurso) {
        this.idCurso = idCurso;
    }
    public String getIdCurso2() {
        return this.idCurso2;
    }
    
    public void setIdCurso2(String idCurso2) {
        this.idCurso2 = idCurso2;
    }
    public String getCodigoCurso() {
        return this.codigoCurso;
    }
    
    public void setCodigoCurso(String codigoCurso) {
        this.codigoCurso = codigoCurso;
    }
    public String getNombreCurso() {
        return this.nombreCurso;
    }
    
    public void setNombreCurso(String nombreCurso) {
        this.nombreCurso = nombreCurso;
    }
    public String getNombreCursoAbreviado() {
        return this.nombreCursoAbreviado;
    }
    
    public void setNombreCursoAbreviado(String nombreCursoAbreviado) {
        this.nombreCursoAbreviado = nombreCursoAbreviado;
    }
    public String getRegistro() {
        return this.registro;
    }
    
    public void setRegistro(String registro) {
        this.registro = registro;
    }
    public Set getSemestreCursos() {
        return this.semestreCursos;
    }
    
    public void setSemestreCursos(Set semestreCursos) {
        this.semestreCursos = semestreCursos;
    }
    public Set getEncuestaDetalles() {
        return this.encuestaDetalles;
    }
    
    public void setEncuestaDetalles(Set encuestaDetalles) {
        this.encuestaDetalles = encuestaDetalles;
    }




}


