package pe.edu.unu.evaluacion.pojo;
// Generated 08/02/2016 11:38:29 PM by Hibernate Tools 4.3.1



/**
 * EncuestaDetalle generated by hbm2java
 */
public class EncuestaDetalle  implements java.io.Serializable {


     private Integer idEncuestaDetalle;
     private Curso curso;
     private Encuesta encuesta;
     private Escuela escuela;
     private Evaluado evaluado;
     private Evaluador evaluador;

    public EncuestaDetalle() {
    }

    public EncuestaDetalle(Curso curso, Encuesta encuesta, Escuela escuela, Evaluado evaluado, Evaluador evaluador) {
       this.curso = curso;
       this.encuesta = encuesta;
       this.escuela = escuela;
       this.evaluado = evaluado;
       this.evaluador = evaluador;
    }
   
    public Integer getIdEncuestaDetalle() {
        return this.idEncuestaDetalle;
    }
    
    public void setIdEncuestaDetalle(Integer idEncuestaDetalle) {
        this.idEncuestaDetalle = idEncuestaDetalle;
    }
    public Curso getCurso() {
        return this.curso;
    }
    
    public void setCurso(Curso curso) {
        this.curso = curso;
    }
    public Encuesta getEncuesta() {
        return this.encuesta;
    }
    
    public void setEncuesta(Encuesta encuesta) {
        this.encuesta = encuesta;
    }
    public Escuela getEscuela() {
        return this.escuela;
    }
    
    public void setEscuela(Escuela escuela) {
        this.escuela = escuela;
    }
    public Evaluado getEvaluado() {
        return this.evaluado;
    }
    
    public void setEvaluado(Evaluado evaluado) {
        this.evaluado = evaluado;
    }
    public Evaluador getEvaluador() {
        return this.evaluador;
    }
    
    public void setEvaluador(Evaluador evaluador) {
        this.evaluador = evaluador;
    }




}


