package pe.edu.unu.evaluacion.pojo;
// Generated 08/02/2016 11:38:29 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Encuesta generated by hbm2java
 */
public class Encuesta  implements java.io.Serializable {


     private Integer idEncuesta;
     private Semestre semestre;
     private Set encuestaPreguntas = new HashSet(0);
     private Set encuestaDetalles = new HashSet(0);

    public Encuesta() {
    }

	
    public Encuesta(Semestre semestre) {
        this.semestre = semestre;
    }
    public Encuesta(Semestre semestre, Set encuestaPreguntas, Set encuestaDetalles) {
       this.semestre = semestre;
       this.encuestaPreguntas = encuestaPreguntas;
       this.encuestaDetalles = encuestaDetalles;
    }
   
    public Integer getIdEncuesta() {
        return this.idEncuesta;
    }
    
    public void setIdEncuesta(Integer idEncuesta) {
        this.idEncuesta = idEncuesta;
    }
    public Semestre getSemestre() {
        return this.semestre;
    }
    
    public void setSemestre(Semestre semestre) {
        this.semestre = semestre;
    }
    public Set getEncuestaPreguntas() {
        return this.encuestaPreguntas;
    }
    
    public void setEncuestaPreguntas(Set encuestaPreguntas) {
        this.encuestaPreguntas = encuestaPreguntas;
    }
    public Set getEncuestaDetalles() {
        return this.encuestaDetalles;
    }
    
    public void setEncuestaDetalles(Set encuestaDetalles) {
        this.encuestaDetalles = encuestaDetalles;
    }




}


