package pe.edu.unu.evaluacion.pojo;
// Generated 08/02/2016 11:38:29 PM by Hibernate Tools 4.3.1



/**
 * EscuelaSemestre generated by hbm2java
 */
public class EscuelaSemestre  implements java.io.Serializable {


     private EscuelaSemestreId id;
     private Escuela escuela;
     private Semestre semestre;

    public EscuelaSemestre() {
    }

    public EscuelaSemestre(EscuelaSemestreId id, Escuela escuela, Semestre semestre) {
       this.id = id;
       this.escuela = escuela;
       this.semestre = semestre;
    }
   
    public EscuelaSemestreId getId() {
        return this.id;
    }
    
    public void setId(EscuelaSemestreId id) {
        this.id = id;
    }
    public Escuela getEscuela() {
        return this.escuela;
    }
    
    public void setEscuela(Escuela escuela) {
        this.escuela = escuela;
    }
    public Semestre getSemestre() {
        return this.semestre;
    }
    
    public void setSemestre(Semestre semestre) {
        this.semestre = semestre;
    }




}


