package pe.edu.unu.evaluacion.pojo;
// Generated 08/02/2016 11:38:29 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Escuela generated by hbm2java
 */
public class Escuela  implements java.io.Serializable {


     private Integer idEscuela;
     private Facultad facultad;
     private String idEscuela2;
     private String nombreEscuela;
     private String descripcion;
     private String abreviatura;
     private String registro;
     private Set encuestaDetalles = new HashSet(0);
     private Set escuelaSemestres = new HashSet(0);

    public Escuela() {
    }

	
    public Escuela(Facultad facultad, String registro) {
        this.facultad = facultad;
        this.registro = registro;
    }
    public Escuela(Facultad facultad, String idEscuela2, String nombreEscuela, String descripcion, String abreviatura, String registro, Set encuestaDetalles, Set escuelaSemestres) {
       this.facultad = facultad;
       this.idEscuela2 = idEscuela2;
       this.nombreEscuela = nombreEscuela;
       this.descripcion = descripcion;
       this.abreviatura = abreviatura;
       this.registro = registro;
       this.encuestaDetalles = encuestaDetalles;
       this.escuelaSemestres = escuelaSemestres;
    }
   
    public Integer getIdEscuela() {
        return this.idEscuela;
    }
    
    public void setIdEscuela(Integer idEscuela) {
        this.idEscuela = idEscuela;
    }
    public Facultad getFacultad() {
        return this.facultad;
    }
    
    public void setFacultad(Facultad facultad) {
        this.facultad = facultad;
    }
    public String getIdEscuela2() {
        return this.idEscuela2;
    }
    
    public void setIdEscuela2(String idEscuela2) {
        this.idEscuela2 = idEscuela2;
    }
    public String getNombreEscuela() {
        return this.nombreEscuela;
    }
    
    public void setNombreEscuela(String nombreEscuela) {
        this.nombreEscuela = nombreEscuela;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getAbreviatura() {
        return this.abreviatura;
    }
    
    public void setAbreviatura(String abreviatura) {
        this.abreviatura = abreviatura;
    }
    public String getRegistro() {
        return this.registro;
    }
    
    public void setRegistro(String registro) {
        this.registro = registro;
    }
    public Set getEncuestaDetalles() {
        return this.encuestaDetalles;
    }
    
    public void setEncuestaDetalles(Set encuestaDetalles) {
        this.encuestaDetalles = encuestaDetalles;
    }
    public Set getEscuelaSemestres() {
        return this.escuelaSemestres;
    }
    
    public void setEscuelaSemestres(Set escuelaSemestres) {
        this.escuelaSemestres = escuelaSemestres;
    }




}


