package pe.edu.unu.evaluacion.pojo;
// Generated 08/02/2016 11:38:29 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Facultad generated by hbm2java
 */
public class Facultad  implements java.io.Serializable {


     private Integer idFacultad;
     private String idFacultad2;
     private String nombreFacultad;
     private String abreviatura;
     private String descripcion;
     private String registro;
     private Set escuelas = new HashSet(0);

    public Facultad() {
    }

	
    public Facultad(String nombreFacultad, String registro) {
        this.nombreFacultad = nombreFacultad;
        this.registro = registro;
    }
    public Facultad(String idFacultad2, String nombreFacultad, String abreviatura, String descripcion, String registro, Set escuelas) {
       this.idFacultad2 = idFacultad2;
       this.nombreFacultad = nombreFacultad;
       this.abreviatura = abreviatura;
       this.descripcion = descripcion;
       this.registro = registro;
       this.escuelas = escuelas;
    }
   
    public Integer getIdFacultad() {
        return this.idFacultad;
    }
    
    public void setIdFacultad(Integer idFacultad) {
        this.idFacultad = idFacultad;
    }
    public String getIdFacultad2() {
        return this.idFacultad2;
    }
    
    public void setIdFacultad2(String idFacultad2) {
        this.idFacultad2 = idFacultad2;
    }
    public String getNombreFacultad() {
        return this.nombreFacultad;
    }
    
    public void setNombreFacultad(String nombreFacultad) {
        this.nombreFacultad = nombreFacultad;
    }
    public String getAbreviatura() {
        return this.abreviatura;
    }
    
    public void setAbreviatura(String abreviatura) {
        this.abreviatura = abreviatura;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getRegistro() {
        return this.registro;
    }
    
    public void setRegistro(String registro) {
        this.registro = registro;
    }
    public Set getEscuelas() {
        return this.escuelas;
    }
    
    public void setEscuelas(Set escuelas) {
        this.escuelas = escuelas;
    }




}


