package pe.edu.unu.evaluacion.pojo;
// Generated 08/02/2016 11:38:29 PM by Hibernate Tools 4.3.1



/**
 * SemestreCursoId generated by hbm2java
 */
public class SemestreCursoId  implements java.io.Serializable {


     private int semestreIdSemestre;
     private int cursoIdCurso;

    public SemestreCursoId() {
    }

    public SemestreCursoId(int semestreIdSemestre, int cursoIdCurso) {
       this.semestreIdSemestre = semestreIdSemestre;
       this.cursoIdCurso = cursoIdCurso;
    }
   
    public int getSemestreIdSemestre() {
        return this.semestreIdSemestre;
    }
    
    public void setSemestreIdSemestre(int semestreIdSemestre) {
        this.semestreIdSemestre = semestreIdSemestre;
    }
    public int getCursoIdCurso() {
        return this.cursoIdCurso;
    }
    
    public void setCursoIdCurso(int cursoIdCurso) {
        this.cursoIdCurso = cursoIdCurso;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SemestreCursoId) ) return false;
		 SemestreCursoId castOther = ( SemestreCursoId ) other; 
         
		 return (this.getSemestreIdSemestre()==castOther.getSemestreIdSemestre())
 && (this.getCursoIdCurso()==castOther.getCursoIdCurso());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getSemestreIdSemestre();
         result = 37 * result + this.getCursoIdCurso();
         return result;
   }   


}


