package pe.edu.unu.evaluacion.pojo;
// Generated 08/02/2016 11:38:29 PM by Hibernate Tools 4.3.1



/**
 * SemestreCurso generated by hbm2java
 */
public class SemestreCurso  implements java.io.Serializable {


     private SemestreCursoId id;
     private Curso curso;
     private Semestre semestre;

    public SemestreCurso() {
    }

    public SemestreCurso(SemestreCursoId id, Curso curso, Semestre semestre) {
       this.id = id;
       this.curso = curso;
       this.semestre = semestre;
    }
   
    public SemestreCursoId getId() {
        return this.id;
    }
    
    public void setId(SemestreCursoId id) {
        this.id = id;
    }
    public Curso getCurso() {
        return this.curso;
    }
    
    public void setCurso(Curso curso) {
        this.curso = curso;
    }
    public Semestre getSemestre() {
        return this.semestre;
    }
    
    public void setSemestre(Semestre semestre) {
        this.semestre = semestre;
    }




}


