package pe.edu.unu.evaluacion.pojo;
// Generated 08/02/2016 11:38:29 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Semestre generated by hbm2java
 */
public class Semestre  implements java.io.Serializable {


     private int idSemestre;
     private String idSemestre2;
     private String nombreSemestre;
     private String anio;
     private String periodo;
     private Date fechaInicio;
     private Date fechaFin;
     private String descripcion;
     private String registro;
     private Set encuestas = new HashSet(0);
     private Set semestreCursos = new HashSet(0);
     private Set escuelaSemestres = new HashSet(0);

    public Semestre() {
    }

	
    public Semestre(int idSemestre, String idSemestre2, String nombreSemestre, String anio, String periodo, String registro) {
        this.idSemestre = idSemestre;
        this.idSemestre2 = idSemestre2;
        this.nombreSemestre = nombreSemestre;
        this.anio = anio;
        this.periodo = periodo;
        this.registro = registro;
    }
    public Semestre(int idSemestre, String idSemestre2, String nombreSemestre, String anio, String periodo, Date fechaInicio, Date fechaFin, String descripcion, String registro, Set encuestas, Set semestreCursos, Set escuelaSemestres) {
       this.idSemestre = idSemestre;
       this.idSemestre2 = idSemestre2;
       this.nombreSemestre = nombreSemestre;
       this.anio = anio;
       this.periodo = periodo;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.descripcion = descripcion;
       this.registro = registro;
       this.encuestas = encuestas;
       this.semestreCursos = semestreCursos;
       this.escuelaSemestres = escuelaSemestres;
    }
   
    public int getIdSemestre() {
        return this.idSemestre;
    }
    
    public void setIdSemestre(int idSemestre) {
        this.idSemestre = idSemestre;
    }
    public String getIdSemestre2() {
        return this.idSemestre2;
    }
    
    public void setIdSemestre2(String idSemestre2) {
        this.idSemestre2 = idSemestre2;
    }
    public String getNombreSemestre() {
        return this.nombreSemestre;
    }
    
    public void setNombreSemestre(String nombreSemestre) {
        this.nombreSemestre = nombreSemestre;
    }
    public String getAnio() {
        return this.anio;
    }
    
    public void setAnio(String anio) {
        this.anio = anio;
    }
    public String getPeriodo() {
        return this.periodo;
    }
    
    public void setPeriodo(String periodo) {
        this.periodo = periodo;
    }
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public String getRegistro() {
        return this.registro;
    }
    
    public void setRegistro(String registro) {
        this.registro = registro;
    }
    public Set getEncuestas() {
        return this.encuestas;
    }
    
    public void setEncuestas(Set encuestas) {
        this.encuestas = encuestas;
    }
    public Set getSemestreCursos() {
        return this.semestreCursos;
    }
    
    public void setSemestreCursos(Set semestreCursos) {
        this.semestreCursos = semestreCursos;
    }
    public Set getEscuelaSemestres() {
        return this.escuelaSemestres;
    }
    
    public void setEscuelaSemestres(Set escuelaSemestres) {
        this.escuelaSemestres = escuelaSemestres;
    }




}


