package pe.edu.unu.evaluacion.pojo;
// Generated 08/02/2016 11:38:29 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idUsuario;
     private String idUsuario2;
     private String rol;
     private String usuario;
     private String contrasenia;
     private String llave;
     private String registro;
     private Set evaluados = new HashSet(0);
     private Set administradors = new HashSet(0);
     private Set evaluadors = new HashSet(0);

    public Usuario() {
    }

	
    public Usuario(String rol, String usuario, String contrasenia, String registro) {
        this.rol = rol;
        this.usuario = usuario;
        this.contrasenia = contrasenia;
        this.registro = registro;
    }
    public Usuario(String idUsuario2, String rol, String usuario, String contrasenia, String llave, String registro, Set evaluados, Set administradors, Set evaluadors) {
       this.idUsuario2 = idUsuario2;
       this.rol = rol;
       this.usuario = usuario;
       this.contrasenia = contrasenia;
       this.llave = llave;
       this.registro = registro;
       this.evaluados = evaluados;
       this.administradors = administradors;
       this.evaluadors = evaluadors;
    }
   
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getIdUsuario2() {
        return this.idUsuario2;
    }
    
    public void setIdUsuario2(String idUsuario2) {
        this.idUsuario2 = idUsuario2;
    }
    public String getRol() {
        return this.rol;
    }
    
    public void setRol(String rol) {
        this.rol = rol;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getContrasenia() {
        return this.contrasenia;
    }
    
    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }
    public String getLlave() {
        return this.llave;
    }
    
    public void setLlave(String llave) {
        this.llave = llave;
    }
    public String getRegistro() {
        return this.registro;
    }
    
    public void setRegistro(String registro) {
        this.registro = registro;
    }
    public Set getEvaluados() {
        return this.evaluados;
    }
    
    public void setEvaluados(Set evaluados) {
        this.evaluados = evaluados;
    }
    public Set getAdministradors() {
        return this.administradors;
    }
    
    public void setAdministradors(Set administradors) {
        this.administradors = administradors;
    }
    public Set getEvaluadors() {
        return this.evaluadors;
    }
    
    public void setEvaluadors(Set evaluadors) {
        this.evaluadors = evaluadors;
    }




}


