-- MySQL Script generated by MySQL Workbench
-- 01/18/16 22:53:12
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema evaluacion
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema evaluacion
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `evaluacion` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `evaluacion` ;

-- -----------------------------------------------------
-- Table `evaluacion`.`facultad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `evaluacion`.`facultad` (
  `id_facultad` INT NOT NULL AUTO_INCREMENT,
  `id_facultad_2` VARCHAR(45) NULL,
  `nombre_facultad` VARCHAR(200) NOT NULL,
  `registro` TEXT NOT NULL,
  PRIMARY KEY (`id_facultad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `evaluacion`.`escuela`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `evaluacion`.`escuela` (
  `id_escuela` INT NOT NULL AUTO_INCREMENT,
  `id_escuela_2` VARCHAR(45) NULL,
  `nombre_escuela` VARCHAR(200) NULL,
  `registro` TEXT NOT NULL,
  `facultad_id_facultad` INT NOT NULL,
  PRIMARY KEY (`id_escuela`),
  INDEX `fk_escuela_facultad1_idx` (`facultad_id_facultad` ASC),
  CONSTRAINT `fk_escuela_facultad1`
    FOREIGN KEY (`facultad_id_facultad`)
    REFERENCES `evaluacion`.`facultad` (`id_facultad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `evaluacion`.`encuesta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `evaluacion`.`encuesta` (
  `id_encuesta` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id_encuesta`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `evaluacion`.`semestre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `evaluacion`.`semestre` (
  `id_semestre` INT NOT NULL,
  `id_semestre_2` VARCHAR(45) NOT NULL,
  `nombre_semestre` VARCHAR(45) NULL,
  `fecha_inicio` DATE NULL,
  `fecha_fin` DATE NULL,
  `registro` TEXT NOT NULL,
  `encuesta_id_encuesta` INT NOT NULL,
  PRIMARY KEY (`id_semestre`),
  INDEX `fk_semestre_encuesta1_idx` (`encuesta_id_encuesta` ASC),
  CONSTRAINT `fk_semestre_encuesta1`
    FOREIGN KEY (`encuesta_id_encuesta`)
    REFERENCES `evaluacion`.`encuesta` (`id_encuesta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `evaluacion`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `evaluacion`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `id_usuario_2` VARCHAR(45) NULL,
  `rol` VARCHAR(45) NOT NULL,
  `usuario` VARCHAR(45) NOT NULL,
  `contrasenia` VARCHAR(45) NOT NULL,
  `llave` VARCHAR(45) NULL,
  `registro` TEXT NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `usuario_UNIQUE` (`usuario` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `evaluacion`.`evaluado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `evaluacion`.`evaluado` (
  `id_evaluado` INT NOT NULL AUTO_INCREMENT,
  `id_evaluado_2` VARCHAR(45) NULL,
  `nombres` VARCHAR(100) NOT NULL,
  `apellido_paterno` VARCHAR(100) NOT NULL,
  `apellido_materno` VARCHAR(100) NOT NULL,
  `sexo` BIT(1) NULL,
  `dni` VARCHAR(12) NOT NULL,
  `ruc` VARCHAR(45) NULL,
  `telefono_fijo` VARCHAR(12) NULL,
  `celular` VARCHAR(12) NULL,
  `email` VARCHAR(45) NULL,
  `tipo_direccion` VARCHAR(45) NULL,
  `direccion` VARCHAR(200) NULL,
  `tipo_localidad` VARCHAR(45) NULL,
  `localidad` VARCHAR(200) NULL,
  `referencia` VARCHAR(200) NULL,
  `registro` TEXT CHARACTER SET 'latin2' COLLATE 'latin2_croatian_ci' NOT NULL,
  `usuario_id_usuario` INT NOT NULL,
  `id_persona` INT NULL,
  PRIMARY KEY (`id_evaluado`),
  INDEX `fk_evaluado_usuario1_idx` (`usuario_id_usuario` ASC),
  UNIQUE INDEX `id_persona_UNIQUE` (`id_persona` ASC),
  CONSTRAINT `fk_evaluado_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `evaluacion`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `evaluacion`.`evaluador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `evaluacion`.`evaluador` (
  `id_evaluador` INT NOT NULL AUTO_INCREMENT,
  `id_evaluador_2` VARCHAR(45) NULL,
  `codigo_universitario` VARCHAR(15) NULL,
  `nombres` VARCHAR(100) NOT NULL,
  `apellido_paterno` VARCHAR(100) NOT NULL,
  `apellido_materno` VARCHAR(100) NOT NULL,
  `sexo` BIT(1) NULL,
  `dni` VARCHAR(12) NOT NULL,
  `ruc` VARCHAR(45) NULL,
  `telefono_fijo` VARCHAR(12) NULL,
  `celular` VARCHAR(12) NULL,
  `email` VARCHAR(45) NULL,
  `tipo_direccion` VARCHAR(45) NULL,
  `direccion` VARCHAR(200) NULL,
  `tipo_localidad` VARCHAR(45) NULL,
  `localidad` VARCHAR(200) NULL,
  `referencia` VARCHAR(200) NULL,
  `registro` TEXT CHARACTER SET 'latin2' COLLATE 'latin2_croatian_ci' NOT NULL,
  `usuario_id_usuario` INT NOT NULL,
  `id_persona` INT NOT NULL,
  PRIMARY KEY (`id_evaluador`),
  INDEX `fk_evaluador_usuario1_idx` (`usuario_id_usuario` ASC),
  UNIQUE INDEX `codigo_universitario_UNIQUE` (`codigo_universitario` ASC),
  UNIQUE INDEX `id_persona_UNIQUE` (`id_persona` ASC),
  CONSTRAINT `fk_evaluador_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `evaluacion`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `evaluacion`.`encuesta_detalle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `evaluacion`.`encuesta_detalle` (
  `id_encuesta_detalle` INT NOT NULL AUTO_INCREMENT,
  `encuesta_id_encuesta` INT NOT NULL,
  `evaluado_id_evaluado` INT NOT NULL,
  `evaluador_id_evaluador` INT NOT NULL,
  `escuela_id_escuela` INT NOT NULL,
  PRIMARY KEY (`id_encuesta_detalle`),
  INDEX `fk_encuesta_detalle_encuesta1_idx` (`encuesta_id_encuesta` ASC),
  INDEX `fk_encuesta_detalle_evaluado1_idx` (`evaluado_id_evaluado` ASC),
  INDEX `fk_encuesta_detalle_evaluador1_idx` (`evaluador_id_evaluador` ASC),
  INDEX `fk_encuesta_detalle_escuela1_idx` (`escuela_id_escuela` ASC),
  CONSTRAINT `fk_encuesta_detalle_encuesta1`
    FOREIGN KEY (`encuesta_id_encuesta`)
    REFERENCES `evaluacion`.`encuesta` (`id_encuesta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_encuesta_detalle_evaluado1`
    FOREIGN KEY (`evaluado_id_evaluado`)
    REFERENCES `evaluacion`.`evaluado` (`id_evaluado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_encuesta_detalle_evaluador1`
    FOREIGN KEY (`evaluador_id_evaluador`)
    REFERENCES `evaluacion`.`evaluador` (`id_evaluador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_encuesta_detalle_escuela1`
    FOREIGN KEY (`escuela_id_escuela`)
    REFERENCES `evaluacion`.`escuela` (`id_escuela`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `evaluacion`.`curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `evaluacion`.`curso` (
  `id_curso` INT NOT NULL AUTO_INCREMENT,
  `id_curso_2` VARCHAR(45) NULL,
  `codigo_curso` VARCHAR(10) NOT NULL,
  `nombre_curso` VARCHAR(200) NOT NULL,
  `nombre_curso_abreviado` VARCHAR(45) NULL,
  `registro` TEXT NOT NULL,
  `encuesta_detalle_id_encuesta_detalle` INT NOT NULL,
  PRIMARY KEY (`id_curso`),
  INDEX `fk_curso_encuesta_detalle1_idx` (`encuesta_detalle_id_encuesta_detalle` ASC),
  CONSTRAINT `fk_curso_encuesta_detalle1`
    FOREIGN KEY (`encuesta_detalle_id_encuesta_detalle`)
    REFERENCES `evaluacion`.`encuesta_detalle` (`id_encuesta_detalle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `evaluacion`.`semestre_curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `evaluacion`.`semestre_curso` (
  `semestre_id_semestre` INT NOT NULL,
  `curso_id_curso` INT NOT NULL,
  INDEX `fk_semestre_curso_semestre1_idx` (`semestre_id_semestre` ASC),
  INDEX `fk_semestre_curso_curso1_idx` (`curso_id_curso` ASC),
  CONSTRAINT `fk_semestre_curso_semestre1`
    FOREIGN KEY (`semestre_id_semestre`)
    REFERENCES `evaluacion`.`semestre` (`id_semestre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_semestre_curso_curso1`
    FOREIGN KEY (`curso_id_curso`)
    REFERENCES `evaluacion`.`curso` (`id_curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `evaluacion`.`administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `evaluacion`.`administrador` (
  `id_administrador` INT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(100) NOT NULL,
  `apellido_paterno` VARCHAR(100) NOT NULL,
  `apellido_materno` VARCHAR(100) NOT NULL,
  `sexo` BIT(1) NULL,
  `dni` VARCHAR(12) NOT NULL,
  `ruc` VARCHAR(45) NULL,
  `telefono_fijo` VARCHAR(12) NULL,
  `celular` VARCHAR(12) NULL,
  `email` VARCHAR(45) NULL,
  `tipo_direccion` VARCHAR(45) NULL,
  `direccion` VARCHAR(200) NULL,
  `tipo_localidad` VARCHAR(45) NULL,
  `localidad` VARCHAR(200) NULL,
  `referencia` VARCHAR(200) NULL,
  `registro` TEXT CHARACTER SET 'latin2' COLLATE 'latin2_croatian_ci' NOT NULL,
  `usuario_id_usuario` INT NOT NULL,
  `id_persona` INT NULL,
  PRIMARY KEY (`id_administrador`),
  INDEX `fk_administrador_usuario1_idx` (`usuario_id_usuario` ASC),
  UNIQUE INDEX `id_persona_UNIQUE` (`id_persona` ASC),
  CONSTRAINT `fk_administrador_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `evaluacion`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `evaluacion`.`persona_historial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `evaluacion`.`persona_historial` (
  `id_persona_historial` INT NOT NULL AUTO_INCREMENT,
  `id_persona_historial_2` VARCHAR(45) NULL,
  `codigo_universitario` VARCHAR(15) NULL,
  `nombres` VARCHAR(100) NOT NULL,
  `apellido_paterno` VARCHAR(100) NOT NULL,
  `apellido_materno` VARCHAR(100) NOT NULL,
  `sexo` BIT(1) NULL,
  `dni` VARCHAR(12) NOT NULL,
  `ruc` VARCHAR(45) NULL,
  `telefono_fijo` VARCHAR(12) NULL,
  `celular` VARCHAR(12) NULL,
  `email` VARCHAR(45) NULL,
  `tipo_direccion` VARCHAR(45) NULL,
  `direccion` VARCHAR(200) NULL,
  `tipo_localidad` VARCHAR(45) NULL,
  `localidad` VARCHAR(200) NULL,
  `referencia` VARCHAR(200) NULL,
  `registro` TEXT CHARACTER SET 'latin2' COLLATE 'latin2_croatian_ci' NOT NULL,
  PRIMARY KEY (`id_persona_historial`),
  UNIQUE INDEX `dni_UNIQUE` (`dni` ASC),
  UNIQUE INDEX `ruc_UNIQUE` (`ruc` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `codigo_universitario_UNIQUE` (`codigo_universitario` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `evaluacion`.`encuesta_pregunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `evaluacion`.`encuesta_pregunta` (
  `id_encuesta_pregunta` INT NOT NULL AUTO_INCREMENT,
  `encuesta_id_encuesta` INT NOT NULL,
  PRIMARY KEY (`id_encuesta_pregunta`),
  INDEX `fk_encuesta_pregunta_encuesta1_idx` (`encuesta_id_encuesta` ASC),
  CONSTRAINT `fk_encuesta_pregunta_encuesta1`
    FOREIGN KEY (`encuesta_id_encuesta`)
    REFERENCES `evaluacion`.`encuesta` (`id_encuesta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `evaluacion`.`escuela_semestre`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `evaluacion`.`escuela_semestre` (
  `escuela_id_escuela` INT NOT NULL,
  `semestre_id_semestre` INT NOT NULL,
  INDEX `fk_escuela_semestre_escuela1_idx` (`escuela_id_escuela` ASC),
  INDEX `fk_escuela_semestre_semestre1_idx` (`semestre_id_semestre` ASC),
  CONSTRAINT `fk_escuela_semestre_escuela1`
    FOREIGN KEY (`escuela_id_escuela`)
    REFERENCES `evaluacion`.`escuela` (`id_escuela`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_escuela_semestre_semestre1`
    FOREIGN KEY (`semestre_id_semestre`)
    REFERENCES `evaluacion`.`semestre` (`id_semestre`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
